server:
  port: 8080

spring:
  application:
    name: MFSB
  datasource:
#    username: postgres
#    password: 1234
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #new added
    url: jdbc:h2:file:~/test
    #C:\Users\bryan\test.mv.db file
  h2:
    console:
      enabled: true
      #new added
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update